<?php


/**
* Theme the custom blocks from vp_api
*/
function block_valeo_alerts($data) {
	return valeo_alerts_output($data);
}


/**
 * Implementation of hook_block().
 */
function vp_blocks_block($op = 'list', $delta = 0, $edit=array()) {
	switch ($op) {
		case 'list': //no switching for delta. always false
  			$blocks['valeo-alerts-ytd'] = array(
				'info' => t('Rate Changes - YTD'),
				'cache' => BLOCK_CACHE_PER_ROLE,
				'status'     => TRUE,
				'weight'     => 0,
				'visibility' => 1,
				'region'	 => 'content_bottom',
			);
  			$blocks['valeo-alerts-new'] = array(
				'info' => t('Rate Changes - Newly Added'),
				'cache' => BLOCK_CACHE_PER_ROLE,
				'status'     => TRUE,
				'weight'     => 0,
				'visibility' => 1,
				'region'	 => 'content_bottom',
			);
			return $blocks;
		case 'view': // switch by delta here to decide what the output should be.
			switch ($delta) {
        		case 'valeo-alerts-ytd':
					$block['subject'] = t('Rate Changes Between ' . date('Y', strtotime('-1 year')) .' and ' .  date('Y', strtotime('-0 year')) . ':'); // Modify to show previous years
					$block['content'] = block_valeo_alerts('ytd');
					break;
        		case 'valeo-alerts-new':
					$block['subject'] = t('Rate Changes Added in Past Two Weeks Between ' . date('Y', strtotime('-1 year')) .' and ' .  date('Y', strtotime('-0 year')) . ':'); // Modify to show previous years
					$block['content'] = block_valeo_alerts('new');
					break;
			}
			return $block;
	}
}