<?php

/**
 * @file
 * Contains vp_forms.module.
 */

 use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function vp_forms_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {

  // Attach javascript library to all forms.
  $form['#attached']['library'][] = 'vp_forms/vp_forms_library';

  switch ($form['#id']) {

    case "views-exposed-form-search-rfp-pitch-analysis-rfp-pitch-analysis-page":

      // Remove the default "all" section if there's a request.
      // This prevents "illegal selection" from happening when there's no "all".
      $request = \Drupal::request();
      if (!is_null($request->get('field_vp_rate_firm_target_id_verf'))) {
        unset($form['field_vp_rate_firm_target_id_verf']['#options']['All']);
      }
      else {
        $form['field_vp_rate_firm_target_id_verf']['#options']['All'] = '- Select -';
      }
      break;

    case "views-exposed-form-search-rates-by-firm-detail-search-rates-by-firm-detail":
    case "views-exposed-form-search-fees-by-firm-search-fees-by-firm-page":
    case "views-exposed-form-search-by-firm-master-search-by-firm-page":

      // Remove the practice area 2 and 3 from the form.
      $form['field_vp_practice_area_2_target_id']['#access'] = TRUE;
      $form['field_vp_practice_area_3_target_id']['#access'] = TRUE;

      // Change the form from a date picker to a dropdown.
      $form['field_vp_filing_fee_dates_value']['min']['#title'] = "Rate Year:<br>From date:";
      $form['field_vp_filing_fee_dates_value']['min']['#type'] = "select";
      $form['field_vp_filing_fee_dates_value']['min']['#multiple'] = FALSE;
      $form['field_vp_filing_fee_dates_value']['min']['#empty_option'] = '-All-';
      $form['field_vp_filing_fee_dates_value']['min']['#options'] = vp_api_year_options_min();
      unset($form['field_vp_filing_fee_dates_value']['min']['#size']);

      // Change the form from a date picker to a dropdown.
      $form['field_vp_filing_fee_dates_value']['max']['#title'] = "<br>To date:";
      $form['field_vp_filing_fee_dates_value']['max']['#type'] = "select";
      $form['field_vp_filing_fee_dates_value']['max']['#multiple'] = FALSE;
      $form['field_vp_filing_fee_dates_value']['max']['#empty_option'] = '-All-';
      $form['field_vp_filing_fee_dates_value']['max']['#options'] = vp_api_year_options_max();
      unset($form['field_vp_filing_fee_dates_value']['max']['#size']);

      // Change the form from textfield to a dropdown.
      $form['field_vp_graduation_value']['min']['#title'] = "Grad Date:<br>From date:";
      $form['field_vp_graduation_value']['min']['#type'] = "select";
      $form['field_vp_graduation_value']['min']['#multiple'] = FALSE;
      $form['field_vp_graduation_value']['min']['#empty_option'] = '-All-';
      $form['field_vp_graduation_value']['min']['#options'] = vp_api_bar_grad_year_options();
      unset($form['field_vp_graduation_value']['min']['#size']);

      // Change the form from textfield to a dropdown.
      $form['field_vp_graduation_value']['max']['#title'] = "<br>To date:";
      $form['field_vp_graduation_value']['max']['#type'] = "select";
      $form['field_vp_graduation_value']['max']['#multiple'] = FALSE;
      $form['field_vp_graduation_value']['max']['#empty_option'] = '-All-';
      // $form['field_vp_graduation_value']['max']['#default_value'] = '2010';
      $form['field_vp_graduation_value']['max']['#options'] = vp_api_bar_grad_year_options();
      unset($form['field_vp_graduation_value']['max']['#size']);

      // Change the form from textfield to a dropdown.
      $form['field_vp_bar_date_value']['min']['#title'] = "Bar Date:<br>From date:";
      $form['field_vp_bar_date_value']['min']['#type'] = "select";
      $form['field_vp_bar_date_value']['min']['#multiple'] = FALSE;
      $form['field_vp_bar_date_value']['min']['#empty_option'] = '-All-';
      $form['field_vp_bar_date_value']['min']['#options'] = vp_api_bar_grad_year_options();
      unset($form['field_vp_bar_date_value']['min']['#size']);

      // Change the form from textfield to a dropdown.
      $form['field_vp_bar_date_value']['max']['#title'] = "<br>To date:";
      $form['field_vp_bar_date_value']['max']['#type'] = "select";
      $form['field_vp_bar_date_value']['max']['#multiple'] = FALSE;
      $form['field_vp_bar_date_value']['max']['#empty_option'] = '-All-';
      $form['field_vp_bar_date_value']['max']['#options'] = vp_api_bar_grad_year_options();
      unset($form['field_vp_bar_date_value']['max']['#size']);

      // Positioning.
      $form['field_vp_rate_firm_target_id_verf']['#weight'] = 5; // firm
      $form['term_node_tid_depth_position']['#weight'] = 20; // position
      $form['field_vp_practice_area_1_target_id']['#weight'] = 30; // practice area
      $form['term_node_tid_depth_location']['#weight'] = 40; // location
      $form['field_vp_graduation_value']['#weight'] = 50; // grad date
      $form['field_vp_bar_date_value']['#weight'] = 65; // bar date
      $form['field_vp_filing_fee_dates_value']['#weight'] = 70; // rate year
      $form['field_vp_case_nature_of_suit_target_id_verf']['#weight'] = 80; // nature of suit

      // Sizing.
      $form['term_node_tid_depth']['#size'] = 8;

      break;

    case "views-exposed-form-search-rates-by-firm-summary-search-rates-by-firm-summary":
    case "views-exposed-form-search-rates-by-firm-summary-rates-search-rates-by-firm-summary":
    case "views-exposed-form-rates-by-firm-summary-individual-rates-by-firm-summary-page":

      // Remove the practice area 2 and 3 from the form.
      $form['field_vp_practice_area_2_target_id']['#access'] = TRUE;
      $form['field_vp_practice_area_3_target_id']['#access'] = TRUE;

      // Change the form from textfield to a dropdown.
      $form['field_vp_graduation_value']['min']['#title'] = "Grad Date:<br>From date:";
      $form['field_vp_graduation_value']['min']['#type'] = "select";
      $form['field_vp_graduation_value']['min']['#multiple'] = FALSE;
      $form['field_vp_graduation_value']['min']['#empty_option'] = '-All-';
      $form['field_vp_graduation_value']['min']['#options'] = vp_api_bar_grad_year_options();
      unset($form['field_vp_graduation_value']['min']['#size']);

      // Change the form from textfield to a dropdown.
      $form['field_vp_graduation_value']['max']['#title'] = "<br>To date:";
      $form['field_vp_graduation_value']['max']['#type'] = "select";
      $form['field_vp_graduation_value']['max']['#multiple'] = FALSE;
      $form['field_vp_graduation_value']['max']['#empty_option'] = '-All-';
      $form['field_vp_graduation_value']['max']['#options'] = vp_api_bar_grad_year_options();
      unset($form['field_vp_graduation_value']['max']['#size']);

      // Change the form from textfield to a dropdown.
      $form['field_vp_bar_date_value']['min']['#title'] = "Bar Date:<br>From date:";
      $form['field_vp_bar_date_value']['min']['#type'] = "select";
      $form['field_vp_bar_date_value']['min']['#multiple'] = FALSE;
      $form['field_vp_bar_date_value']['min']['#empty_option'] = '-All-';
      $form['field_vp_bar_date_value']['min']['#options'] = vp_api_bar_grad_year_options();
      unset($form['field_vp_bar_date_value']['min']['#size']);

      // Change the form from textfield to a dropdown.
      $form['field_vp_bar_date_value']['max']['#title'] = "<br>To date:";
      $form['field_vp_bar_date_value']['max']['#type'] = "select";
      $form['field_vp_bar_date_value']['max']['#multiple'] = FALSE;
      $form['field_vp_bar_date_value']['max']['#empty_option'] = '-All-';
      $form['field_vp_bar_date_value']['max']['#options'] = vp_api_bar_grad_year_options();
      unset($form['field_vp_bar_date_value']['max']['#size']);

      // Positioning.
      $form['field_vp_rate_firm_target_id_verf']['#weight'] = 10; // firm
      $form['term_node_tid_depth_position']['#weight'] = 20; // position
      $form['field_vp_practice_area_1_target_id']['#weight'] = 30; // practice area
      $form['term_node_tid_depth_location']['#weight'] = 40; // location
      $form['field_vp_graduation_value']['#weight'] = 50;
      $form['field_vp_bar_date_value']['#weight'] = 55;

      // Sizing.
      $form['term_node_tid_depth']['#size'] = 8;

      break;

    case "views-exposed-form-search-fees-by-company-search-fees-by-company-page":

      // Remove the practice area 2 and 3 from the form.
      $form['field_vp_practice_area_2_target_id']['#access'] = TRUE;
      $form['field_vp_practice_area_3_target_id']['#access'] = TRUE;

      // Change the form from a date picker to a dropdown.
      $form['field_vp_filing_fee_dates_value']['min']['#title'] = "Rate Year:<br>From date:";
      $form['field_vp_filing_fee_dates_value']['min']['#type'] = "select";
      $form['field_vp_filing_fee_dates_value']['min']['#multiple'] = FALSE;
      $form['field_vp_filing_fee_dates_value']['min']['#empty_option'] = '-All-';
      $form['field_vp_filing_fee_dates_value']['min']['#options'] = vp_api_year_options_min();
      unset($form['field_vp_filing_fee_dates_value']['min']['#size']);

      // Change the form from a date picker to a dropdown.
      $form['field_vp_filing_fee_dates_value']['max']['#title'] = "<br>To date:";
      $form['field_vp_filing_fee_dates_value']['max']['#type'] = "select";
      $form['field_vp_filing_fee_dates_value']['max']['#multiple'] = FALSE;
      $form['field_vp_filing_fee_dates_value']['max']['#empty_option'] = '-All-';
      $form['field_vp_filing_fee_dates_value']['max']['#options'] = vp_api_year_options_max();
      unset($form['field_vp_filing_fee_dates_value']['max']['#size']);

      // Positioning.
      $form['field_vp_company_industry_target_id']['#weight'] = 10; // industry
      $form['term_node_tid_depth_position']['#weight'] = 20; // position
      $form['field_vp_practice_area_1_target_id']['#weight'] = 30; // practice area
      $form['term_node_tid_depth_location']['#weight'] = 40; // location
      $form['field_vp_filing_fee_dates_value']['#weight'] = 50; // fee year
      $form['field_vp_rate_company_target_id_verf']['#weight'] = 60; // company
      $form['field_vp_rate_company_target_id_verf_1']['#weight'] = 70; // referenced company

      // Sizing.
      $form['term_node_tid_depth']['#size'] = 8;

      break;

    case "views-exposed-form-search-ci-database-search-ci-database-page":

      // Change the form from a date picker to a dropdown.
      $form['field_vp_filing_fee_dates_value']['min']['#title'] = "Rate Year:<br>From date:";
      $form['field_vp_filing_fee_dates_value']['min']['#type'] = "select";
      $form['field_vp_filing_fee_dates_value']['min']['#multiple'] = FALSE;
      $form['field_vp_filing_fee_dates_value']['min']['#empty_option'] = '-All-';
      $form['field_vp_filing_fee_dates_value']['min']['#options'] = vp_api_year_options_min();
      unset($form['field_vp_filing_fee_dates_value']['min']['#size']);

      // Change the form from a date picker to a dropdown.
      $form['field_vp_filing_fee_dates_value']['max']['#title'] = "<br>To date:";
      $form['field_vp_filing_fee_dates_value']['max']['#type'] = "select";
      $form['field_vp_filing_fee_dates_value']['max']['#multiple'] = FALSE;
      $form['field_vp_filing_fee_dates_value']['max']['#empty_option'] = '-All-';
      $form['field_vp_filing_fee_dates_value']['max']['#options'] = vp_api_year_options_max();
      unset($form['field_vp_filing_fee_dates_value']['max']['#size']);

      break;

  }

}

/**
 * Implements hook_form_alter().
 */
function vp_forms_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $form['#attached']['library'][] = 'vp_forms/vp_forms_library';
  /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
  $formObject = $form_state->getFormObject();
  if ($formObject instanceof \Drupal\Core\Entity\EntityFormInterface) {
    $entity = $formObject->getEntity();
    if (
      $entity->getEntityTypeId() === 'node'
      && in_array($entity->bundle(), ['vp_type_saved_search'])
    ) {
      $form['#attached']['library'][] = 'vp_forms/vp_forms_library';
    }
  }

  switch ($form_id) {
    case "node_vp_type_rate_form":

      $form['#attached']['library'][] = 'vp_forms/vp_forms_library';
      // $form['field_vp_rate_individual'] = array(
      //   '#type' => 'select2',
      // );

      break;
  }

}
