<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_preprocess_views_view_table().
 */
function vp_views_preprocess_views_view_table(&$variables) {

  if (isset($_GET['year'])) {
    $year = $_GET['year'];
    $last_year = $year - 1;
    $variables['header']['field_vp_rate_hourly']['content'] = $year . ' Rate';
    $variables['header']['field_vp_rate_previous']['content'] = $last_year . ' Rate';
  }

  $view = $variables['view'];

  switch ($view->current_display) {

    case 'saved_search_detail_block':

      // Get this node.
      $node = \Drupal::routeMatch()->getParameter('node');

      if ($node) {
        // Get variables from view
        $fields = &$view->field;
        $options = &$view->style_plugin->options;

        // Get the vocabulary name.
        $vid = 'search_columns';

        // Use the entity manager to load that taxonomy tree.
        $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);

        // Get all the term ids for the Search Columns vocabulary.
        foreach ($terms as $term) {
          $term_ids[] = $term->tid;
        }

        // Get the display term taxonomy referenced entities.
        $display_terms_entities = $node->get('field_vp_search_display_columns')->referencedEntities();

        // Loop through the entities referred in the node and assign those values
        // to an array.
        $selected_ids = [];
        foreach ($display_terms_entities as $term) {
          $selected_ids[] = $term->id();
        }

        // Get the difference between available and selected terms.
        $term_values = [];
        foreach (array_diff($term_ids, $selected_ids) as $term_id) {
          $term_object = Term::load($term_id);
          $term_values[] = $term_object->field_search_column_key->value;
        }

        // Go through all the columns, delete the column headers, values
        // if they're in the term list.
        // Only hide fields if the array key '2705' (All Fields)
        // is not selected.
        if (!in_array('2705', $selected_ids)) {
          foreach ($options['columns'] as $column => $value) {
            foreach ($variables['rows'] as &$column_items) {
              if (in_array($column, $term_values)) {
                unset($column_items['columns'][$column]);
                unset($variables['header'][$column]);
              }
            }
          }
        }
      }
      break;
  }

}

/**
 * Implements hook_views_query_alter().
 */
function vp_views_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  switch ($view->storage->id()) {
    case 'search_rates_by_firm_summary_rates':
    case 'rates_by_firm_summary_individual':
    case 'firm_history':
      $query->addField('node_field_data', 'nid', '', ['function' => 'groupby']);
      $query->addGroupBy('node_field_data.nid');
      break;
  }

  $view_ids = [
    'search_by_firm',
    'search_rates_by_firm_summary_rates',
    'search_rates_by_firm_detail',
    'search_fees_by_firm',
    'search_fees_by_company',
  ];
  $view_displays = [
    'data_export_xls',
  ];


  if (in_array($view->id(), $view_ids) && $view->exposed_data && $view->current_display != 'data_export_xls') {
    // Get the value of the exposed filter Practice Area 1,
    // set to NULL if it doesn't exist.
    $pa1 = $view->exposed_data['field_vp_practice_area_1_target_id'] ? $view->exposed_data['field_vp_practice_area_1_target_id'] : NULL;

    // If there is no exposed data for practice area 1.
    if (!isset($pa1)) {
      // Get rid of the practice area "OR" block entirely.
      unset($query->where[2]);

      // We add practice areas with default values in the view so the
      // proper relationships are created.
      // Get the tableQueue so we can manipulate it,
      // and clear the default practice area values.
      $tables =& $query->getTableQueue();
      unset($tables['node_field_data_node__field_vp_rate_individual__node__field_vp_practice_area_2']);
      unset($tables['node_field_data_node__field_vp_rate_individual__node__field_vp_practice_area_3']);
    }
    else {
      // Traverse through the 'where' part of the query,
      // eliminate the value of practice area 2 and 3,
      // add value of practice area 1 to practice areas 2 and 3.
      foreach ($query->where as &$condition_group) {
        foreach ($condition_group['conditions'] as &$condition) {

          if ($condition['field'] == 'node_field_data_node__field_vp_rate_individual__node__field_vp_practice_area_2.field_vp_practice_area_2_target_id = :node__field_vp_practice_area_2_field_vp_practice_area_2_target_id') {
            $condition['value'][':node__field_vp_practice_area_2_field_vp_practice_area_2_target_id'] = NULL;
          }
          if ($condition['field'] == 'node_field_data_node__field_vp_rate_individual__node__field_vp_practice_area_3.field_vp_practice_area_3_target_id = :node__field_vp_practice_area_3_field_vp_practice_area_3_target_id') {
            $condition['value'][':node__field_vp_practice_area_3_field_vp_practice_area_3_target_id'] = NULL;
          }
          if ($condition['field'] == 'node_field_data_node__field_vp_rate_individual__node__field_vp_practice_area_1.field_vp_practice_area_1_target_id = :node__field_vp_practice_area_1_field_vp_practice_area_1_target_id') {
            $field = 'node_field_data_node__field_vp_rate_individual__node__field_vp_practice_area_2.field_vp_practice_area_2_target_id';
            $field2 = 'node_field_data_node__field_vp_rate_individual__node__field_vp_practice_area_3.field_vp_practice_area_3_target_id';
            $value = $pa1;
            $operator = '=';
            $query->addWhere(2, $field, $value, $operator);
            $query->addWhere(2, $field2, $value, $operator);
          }
        }
      }
    }
  }
}