<?php

/**
 * @file
 * Views hooks for Valeo Partners.
 */

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_preprocess_views_view_table().
 */
function vp_views_preprocess_views_view_table(&$variables) {

  if (isset($_GET['year'])) {
    $year = $_GET['year'];
    $last_year = $year - 1;
    $variables['header']['field_vp_rate_hourly']['content'] = $year . ' Rate';
    $variables['header']['field_vp_rate_previous']['content'] = $last_year . ' Rate';
  }

  $view = $variables['view'];

  switch ($view->current_display) {

    case 'saved_search_detail_block':

      // Get this node.
      $node = \Drupal::routeMatch()->getParameter('node');

      if ($node) {
        // Get variables from view.
        $fields = &$view->field;
        $options = &$view->style_plugin->options;

        // Get the vocabulary name.
        $vid = 'search_columns';

        // Use the entity manager to load that taxonomy tree.
        $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);

        // Get all the term ids for the Search Columns vocabulary.
        foreach ($terms as $term) {
          $term_ids[] = $term->tid;
        }

        // Get the display term taxonomy referenced entities.
        $display_terms_entities = $node->get('field_vp_search_display_columns')->referencedEntities();

        // Loop through the entities referred in the node and assign those values
        // to an array.
        $selected_ids = [];
        foreach ($display_terms_entities as $term) {
          $selected_ids[] = $term->id();
        }

        // Get the difference between available and selected terms.
        $term_values = [];
        foreach (array_diff($term_ids, $selected_ids) as $term_id) {
          $term_object = Term::load($term_id);
          $term_values[] = $term_object->field_search_column_key->value;
        }

        // Go through all the columns, delete the column headers, values
        // if they're in the term list.
        // Only hide fields if the array key '2705' (All Fields)
        // is not selected.
        if (!in_array('2705', $selected_ids)) {
          foreach ($options['columns'] as $column => $value) {
            foreach ($variables['rows'] as &$column_items) {
              if (in_array($column, $term_values)) {
                unset($column_items['columns'][$column]);
                unset($variables['header'][$column]);
              }
            }
          }
        }
      }
      break;
  }

}

/**
 * Implements hook_views_query_alter().
 */
function vp_views_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  // Add group by to eliminate duplicate records.
  switch ($view->storage->id()) {
    case 'search_rates_by_firm_summary_rates':
    case 'rates_by_firm_summary_individual':
    case 'firm_history':
      $query->addField('node_field_data', 'nid', '', ['function' => 'groupby']);
      $query->addGroupBy('node_field_data.nid');
      break;

  }
}
