<?php
// $Id$

/**
 * @file
 *   Installs the schema for the Valeo module.
 */

/**
 * Implementation of hook_install().
 */
function valeomod_install() {
	variable_set('valeomod_alertsrunning', 0);
}

/**
 * Implementation of hook_uninstall().
 */
function valeomod_uninstall() {
	// Delete all the valeomod variables and then clear the variable cache
	db_query("DELETE FROM {variable} WHERE name LIKE 'valeomod_%'");
	cache_clear_all('variables', 'cache');
}
