name: Configuration development
type: module
description: 'Helps developers work with configuration.'
package: Configuration
# version: VERSION
# core: 8.x
configure: config_devel.settings

# Information added by Drupal.org packaging script on 2019-07-11
version: '8.x-1.3'
core: '8.x'
project: 'config_devel'
datestamp: 1562862187
