content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  rate_report_user: 4
  superuser: 5
  pilot_account: 6
  data_entry: 7
  alerts_add_on: 8
  company_industry_add_on: 9
  full_database_download_add_on: 10
  firm_rate_profile_add_on: 11
  fee_search_add_on: 12
  nos_add_on: 13
  download_add_on: 14
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
