module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  computed_field: 0
  config: 0
  contact: 0
  content_access: 0
  content_moderation: 0
  contextual: 0
  contextual_range_filter: 0
  csv_importer: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  date_popup: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  inline_form_errors: 0
  layout_discovery: 0
  link: 0
  menu_token: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_upgrade: 0
  module_filter: 0
  multiselect: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_library: 0
  paragraphs_type_permissions: 0
  path: 0
  quickedit: 0
  range: 0
  rdf: 0
  redirect_after_login: 0
  rest: 0
  rules: 0
  search: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  shs: 0
  smtp: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  vefl_bef: 0
  verf: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  vp_api: 0
  vp_computed_fields: 0
  vp_views: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  xls_serialization: 0
  yearonly: 0
  contribute: 1
  menu_link_content: 1
  pathauto: 1
  menu_link_weight: 10
  views: 10
  paragraphs: 11
  publication_date: 99
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  yorkshire: 0
  adminimal_theme: 0
  valeo_classic: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
