id: firm_to_paragraph
label: 'Import d6 field to paragraph'
langcode: en
status: true
dependencies:
  enforced:
    module:
      - valeo_partners_migrations
migration_group: valeomiggroup
source:
  plugin: d6_node
  node_type: individual
destination:
  plugin: 'entity_reference_revisions:paragraph'
  default_bundle: employment_history
field_vp_employment_history:
  plugin: para_firm
  source:
    - field_individual_firm
    - field_individual_partnerdate
    - field_individual_firmdate
migration_dependencies:
  required: {  }
  optional: {  }
_core:
  default_config_hash: AK1Fzo-08SyQbf5alcG0bQfYOntaO2mXT7I8LHK_cAk
