status: 1
pattern: '[node:field_vp_contact_firstname] [node:field_vp_contact_middleinitial] [node:field_vp_contact_lastname]'
php: false
escape: false
dependencies:
  config:
    - node.type.vp_type_contact
