palette:
  top: '#ffffff'
  bottom: '#ffffff'
  bg: '#ffffff'
  sidebar: '#B2C2D1'
  sidebarborders: '#B2C2D1'
  footer: '#0B3B6B'
  titleslogan: '#0B3B6B'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/valeo_classic-8a8f7e2e/logo.svg'
stylesheets:
  - 'public://color/valeo_classic-8a8f7e2e/colors.css'
files:
  - 'public://color/valeo_classic-8a8f7e2e/logo.svg'
  - 'public://color/valeo_classic-8a8f7e2e/colors.css'
