content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  rate_report_user: 4
  superuser: 5
  pilot_account: 6
  data_entry: 7
  alerts_add_on: 8
  company_industry_add_on: 9
  full_database_download_add_on: 10
  firm_rate_profile_add_on: 11
  fee_search_add_on: 12
  nos_add_on: 13
  download_add_on: 14
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_node_type:
  vp_type_saved_search: 'a:2:{s:8:"view_own";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}s:4:"view";a:4:{i:0;s:13:"administrator";i:1;s:16:"rate_report_user";i:2;s:9:"superuser";i:3;s:10:"data_entry";}}'
  vp_type_rate: 'a:2:{s:8:"view_own";a:4:{i:0;s:13:"authenticated";i:1;s:16:"rate_report_user";i:2;s:9:"superuser";i:3;s:10:"data_entry";}s:4:"view";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}}'
  vp_type_individual: 'a:2:{s:8:"view_own";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}s:4:"view";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}}'
  vp_type_firm: 'a:2:{s:8:"view_own";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}s:4:"view";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}}'
  vp_type_filing: 'a:2:{s:8:"view_own";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}s:4:"view";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}}'
  vp_type_contact: 'a:2:{s:8:"view_own";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}s:4:"view";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}}'
  vp_type_case: 'a:2:{s:8:"view_own";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}s:4:"view";a:5:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:16:"rate_report_user";i:3;s:9:"superuser";i:4;s:10:"data_entry";}}'
  vp_type_company: 'a:2:{s:8:"view_own";a:4:{i:0;s:13:"authenticated";i:1;s:16:"rate_report_user";i:2;s:9:"superuser";i:3;s:10:"data_entry";}s:4:"view";a:4:{i:0;s:13:"authenticated";i:1;s:16:"rate_report_user";i:2;s:9:"superuser";i:3;s:10:"data_entry";}}'
  article: 'a:2:{s:8:"view_own";a:4:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:9:"superuser";i:3;s:10:"data_entry";}s:4:"view";a:4:{i:0;s:13:"authenticated";i:1;s:13:"administrator";i:2;s:9:"superuser";i:3;s:10:"data_entry";}}'
