printfriendly_image: printfriendly-pdf-button-nobg-md.png
db_version: 1
printfriendly_display:
  article: 0
  page: 0
  vp_type_case: 0
  vp_type_company: 0
  vp_type_contact: 0
  vp_type_filing: 0
  vp_type_firm: 0
  vp_type_individual: 0
  vp_type_rate: 0
  vp_type_saved_search: 0
  teaser: 0
printfriendly_page_header: default_logo
printfriendly_page_custom_header: ''
printfriendly_tagline: ''
printfriendly_click_delete: '0'
printfriendly_images: '0'
printfriendly_image_style: right
printfriendly_email: '1'
printfriendly_pdf: '0'
printfriendly_print: '0'
printfriendly_custom_css: ''
custom_button_img_url: ''
